const types = [
  { label: "Golf", name: "Golf", id: 1 },
  { label: "Tennis", name: "Tennis", id: 2 },
  { label: "Cricket", name: "Cricket", id: 3 },
  { label: "Basketball", name: "Basketball", id: 4 },
  { label: "Baseball", name: "Baseball", id: 5 },
  { label: "American Football", name: "American Football", id: 6 },
  { label: "Aquatics", name: "Aquatics", id: 7 },
  { label: "Archery", name: "Archery", id: 8 },
  { label: "Automobile Racing", name: "Automobile Racing", id: 9 },
  { label: "Badminton", name: "Badminton", id: 10 },
  { label: "Beach Volleyball", name: "Beach Volleyball", id: 11 },
  { label: "Bobsleigh", name: "Bobsleigh", id: 12 },
  { label: "Body Building", name: "Body Building", id: 13 },
  { label: "Boxing", name: "Boxing", id: 14 },
  { label: "Cross Country Running", name: "Cross Country Running", id: 15 },
  { label: "Cross Country Skiing", name: "Cross Country Skiing", id: 16 },
  { label: "Curling", name: "Curling", id: 17 },
  { label: "Cycling", name: "Cycling", id: 18 },
  { label: "Darts", name: "Darts", id: 19 },
  { label: "Decathlon", name: "Decathlon", id: 20 },
  { label: "Down Hill Skiing", name: "Down Hill Skiing", id: 21 },
  { label: "Equestrianism", name: "Equestrianism", id: 22 },
  { label: "eSports", name: "eSports", id: 23 },
  { label: "Fencing", name: "Fencing", id: 24 },
  { label: "Field Hockey", name: "Field Hockey", id: 25 },
  { label: "Figure Skating", name: "Figure Skating", id: 26 },
  { label: "Gymnastics", name: "Gymnastics", id: 27 },
  { label: "Ice Hockey", name: "Ice Hockey", id: 28 },
  { label: "Martial Arts", name: "Martial Arts", id: 29 },
  { label: "Mixed Martial Arts", name: "Mixed Martial Arts", id: 30 },
  { label: "Modern Pentathlon", name: "Modern Pentathlon", id: 31 },
  { label: "Motorcycle Racing", name: "Motorcycle Racing", id: 32 },
  { label: "Netball", name: "Netball", id: 33 },
  { label: "Polo", name: "Polo", id: 34 },
  { label: "Racquetball", name: "Racquetball", id: 35 },
  { label: "Rowing", name: "Rowing", id: 36 },
  { label: "Rugby", name: "Rugby", id: 37 },
  { label: "Sailing", name: "Sailing", id: 38 },
  { label: "Softball", name: "Softball", id: 39 },
  { label: "Shooting", name: "Shooting", id: 40 },
  { label: "Skateboarding", name: "Skateboarding", id: 41 },
  { label: "Skeet Shooting", name: "Skeet Shooting", id: 42 },
  { label: "Skeleton", name: "Skeleton", id: 43 },
  { label: "Snow Boarding", name: "Snow Boarding", id: 44 },
  { label: "Soccer (Football)", name: "Soccer (Football)", id: 45 },
  { label: "Squash", name: "Squash", id: 46 },
  { label: "Surfing", name: "Surfing", id: 47 },
  { label: "Swimming", name: "Swimming", id: 48 },
  { label: "Track and Field", name: "Track and Field", id: 49 }
]

export default types