const types = [
  { label: "Golf", value: "Golf", id: 1 },
  { label: "Tennis", value: "Tennis", id: 2 },
  { label: "Cricket", value: "Cricket", id: 3 },
  { label: "Basketball", value: "Basketball", id: 4 },
  { label: "Baseball", value: "Baseball", id: 5 },
  { label: "American Football", value: "American Football", id: 6 },
  { label: "Aquatics", value: "Aquatics", id: 7 },
  { label: "Archery", value: "Archery", id: 8 },
  { label: "Automobile Racing", value: "Automobile Racing", id: 9 },
  { label: "Badminton", value: "Badminton", id: 10 },
  { label: "Beach Volleyball", value: "Beach Volleyball", id: 11 },
  { label: "Bobsleigh", value: "Bobsleigh", id: 12 },
  { label: "Body Building", value: "Body Building", id: 13 },
  { label: "Boxing", value: "Boxing", id: 14 },
  { label: "Cross Country Running", value: "Cross Country Running", id: 15 },
  { label: "Cross Country Skiing", value: "Cross Country Skiing", id: 16 },
  { label: "Curling", value: "Curling", id: 17 },
  { label: "Cycling", value: "Cycling", id: 18 },
  { label: "Darts", value: "Darts", id: 19 },
  { label: "Decathlon", value: "Decathlon", id: 20 },
  { label: "Down Hill Skiing", value: "Down Hill Skiing", id: 21 },
  { label: "Equestrianism", value: "Equestrianism", id: 22 },
  { label: "eSports", value: "eSports", id: 23 },
  { label: "Fencing", value: "Fencing", id: 24 },
  { label: "Field Hockey", value: "Field Hockey", id: 25 },
  { label: "Figure Skating", value: "Figure Skating", id: 26 },
  { label: "Gymnastics", value: "Gymnastics", id: 27 },
  { label: "Ice Hockey", value: "Ice Hockey", id: 28 },
  { label: "Martial Arts", value: "Martial Arts", id: 29 },
  { label: "Mixed Martial Arts", value: "Mixed Martial Arts", id: 30 },
  { label: "Modern Pentathlon", value: "Modern Pentathlon", id: 31 },
  { label: "Motorcycle Racing", value: "Motorcycle Racing", id: 32 },
  { label: "Netball", value: "Netball", id: 33 },
  { label: "Polo", value: "Polo", id: 34 },
  { label: "Racquetball", value: "Racquetball", id: 35 },
  { label: "Rowing", value: "Rowing", id: 36 },
  { label: "Rugby", value: "Rugby", id: 37 },
  { label: "Sailing", value: "Sailing", id: 38 },
  { label: "Softball", value: "Softball", id: 39 },
  { label: "Shooting", value: "Shooting", id: 40 },
  { label: "Skateboarding", value: "Skateboarding", id: 41 },
  { label: "Skeet Shooting", value: "Skeet Shooting", id: 42 },
  { label: "Skeleton", value: "Skeleton", id: 43 },
  { label: "Snow Boarding", value: "Snow Boarding", id: 44 },
  { label: "Soccer (Football)", value: "Soccer (Football)", id: 45 },
  { label: "Squash", value: "Squash", id: 46 },
  { label: "Surfing", value: "Surfing", id: 47 },
  { label: "Swimming", value: "Swimming", id: 48 },
  { label: "Track and Field", value: "Track and Field", id: 49 }
]

export default types