const types = [
  { label: "Golf", value: "golf", id: 1 },
  { label: "Tennis", value: "tennis", id: 2 },
  { label: "Cricket", value: "cricket", id: 3 },
  { label: "Basketball", value: "basketball", id: 4 },
  { label: "Baseball", value: "baseball", id: 5 },
  { label: "American Football", value: "american_football", id: 6 },
  { label: "Aquatics", value: "aquatics", id: 7 },
  { label: "Archery", value: "archery", id: 8 },
  { label: "Automobile Racing", value: "automobile_racing", id: 9 },
  { label: "Badminton", value: "badminton", id: 10 },
  { label: "Beach Volleyball", value: "beach_volleyball", id: 11 },
  { label: "Bobsleigh", value: "bobsleigh", id: 12 },
  { label: "Body Building", value: "body_building", id: 13 },
  { label: "Boxing", value: "boxing", id: 14 },
  { label: "Cross Country Running", value: "cross_country_running", id: 15 },
  { label: "Cross Country Skiing", value: "cross_country_skiing", id: 16 },
  { label: "Curling", value: "curling", id: 17 },
  { label: "Cycling", value: "cycling", id: 18 },
  { label: "Darts", value: "darts", id: 19 },
  { label: "Decathlon", value: "decathlon", id: 20 },
  { label: "Down Hill Skiing", value: "down_hill_skiing", id: 21 },
  { label: "Equestrianism", value: "equestrianism", id: 22 },
  { label: "eSports", value: "esports", id: 23 },
  { label: "Fencing", value: "fencing", id: 24 },
  { label: "Field Hockey", value: "field_hockey", id: 25 },
  { label: "Figure Skating", value: "figure_skating", id: 26 },
  { label: "Gymnastics", value: "gymnastics", id: 27 },
  { label: "Ice Hockey", value: "ice_hockey", id: 28 },
  { label: "Martial Arts", value: "martial_arts", id: 29 },
  { label: "Mixed Martial Arts", value: "mixed_martial_arts", id: 30 },
  { label: "Modern Pentathlon", value: "modern_pentathlon", id: 31 },
  { label: "Motorcycle Racing", value: "motorcycle_racing", id: 32 },
  { label: "Netball", value: "netball", id: 33 },
  { label: "Polo", value: "polo", id: 34 },
  { label: "Racquetball", value: "racquetball", id: 35 },
  { label: "Rowing", value: "rowing", id: 36 },
  { label: "Rugby", value: "rugby", id: 37 },
  { label: "Sailing", value: "sailing", id: 38 },
  { label: "Softball", value: "softball", id: 39 },
  { label: "Shooting", value: "shooting", id: 40 },
  { label: "Skateboarding", value: "skateboarding", id: 41 },
  { label: "Skeet Shooting", value: "skeet_shooting", id: 42 },
  { label: "Skeleton", value: "skeleton", id: 43 },
  { label: "Snow Boarding", value: "snow_boarding", id: 44 },
  { label: "Soccer (Football)", value: "soccer_football", id: 45 },
  { label: "Squash", value: "squash", id: 46 },
  { label: "Surfing", value: "surfing", id: 47 },
  { label: "Swimming", value: "swimming", id: 48 },
  { label: "Track and Field", value: "track_and_field", id: 49 }
]

export default types